window.SITE_CONTENT = {
  profile: {
    name: 'loren',
    siteTitle: "Loren's Galaxy",
    eyebrow: '一块小小的互联网自留地',
    intro: '写代码，做产品，记录有意思的想法。',
    description: '相信好的东西来自好奇心，也来自把一个小想法认真做完。这里是我的作品、文字，和一些尚未成形的灵感。',
    role: 'Bytedance Seed AI Infra Engineer',
    location: '中国 上海市',
    locationEn: 'CHINA · SHANGHAI',
    note: '保持好奇，持续创造。',
    noteAlt: 'Carpe diem · 此心安处是吾乡。',
    now: '正在把脑海里的想法，变成可以被使用的小东西。',
    nowNote: '慢一点，也没关系。',
    email: '',
    github: 'https://github.com/Jeff-Zzh',
    demo: true,
  },
  about: {
    lead: '我喜欢把模糊的问题拆开，再把答案做成可以被看见、被使用的东西。',
    paragraphs: [
      '目前关注产品、工程与人工智能之间的交叉地带。比起追逐复杂，我更在意一个想法是否清楚、一个工具是否真的让事情变简单。',
      '工作之外，我会写下观察，做一些小项目，也会为没有明确用途的好奇心留出时间。',
    ],
    facts: [
      { label: '当前职位', profile: 'role' },
      { label: '所在地区', profile: 'location' },
      { label: '正在探索', value: 'AI 产品与 Agent 系统' },
      { label: '喜欢的工作方式', value: '从原型开始，持续迭代' },
      { label: '长期兴趣', value: '技术、设计、写作' },
      { label: '所在时区', value: 'UTC+8' },
    ],
  },
  experiments: [
    {
      id: 'signal-garden',
      name: 'Signal Garden',
      status: '进行中',
      description: '把每天遇见的信息整理成一座缓慢生长的知识花园。',
      tags: ['AI', 'Knowledge'],
    },
    {
      id: 'quiet-interface',
      name: 'Quiet Interface',
      status: '概念',
      description: '探索更少打扰、更少选择，却能准确完成任务的界面。',
      tags: ['Design', 'Prototype'],
    },
    {
      id: 'tiny-automations',
      name: 'Tiny Automations',
      status: '持续更新',
      description: '收集那些只需几十行代码，却能每天节省一点时间的自动化。',
      tags: ['Scripts', 'Tools'],
    },
  ],
  experience: [
    {
      company: '字节跳动',
      logo: './assets/bytedance-logo.png',
      logoAlt: 'ByteDance',
      employmentType: '正式',
      location: '中国 上海市',
      workMode: '现场办公',
      start: '2024-04',
      roles: [
        {
          title: 'Seed AI Infra Engineer',
          logo: './assets/bytedance-seed-logo.png',
          logoAlt: 'ByteDance Seed',
          logoKind: 'seed',
          start: '2026-01',
          current: true,
          highlights: [
            'ML Infra Platform',
            'Agentic ML Infra & Agent',
            'Multi-Agent Long Horizon Framework',
            'Harness',
          ],
          skills: ['Go', 'Python'],
        },
        {
          title: 'Ads Infra Engineer',
          logo: './assets/ocean-engine-logo.png',
          logoAlt: '巨量引擎 Ocean Engine',
          logoKind: 'ocean-engine',
          start: '2024-04',
          end: '2025-12',
          highlights: [
            '巨量有戏 AIGC：ipgen.ohayoo.cn 项目 0→2.5 期，担任后端架构与算法工程负责人。',
          ],
          skills: ['Java', 'React.js'],
        },
      ],
    },
  ],
  journey: [
    {
      period: '2023.09 — 2025.06',
      title: '西安电子科技大学',
      degree: '硕士',
      major: '计算机技术',
    },
    {
      period: '2019.09 — 2023.06',
      title: '西安电子科技大学',
      degree: '本科',
      major: '软件工程',
    },
  ],
  library: [
    { type: '书', title: 'The Design of Everyday Things', note: '设计应该让正确的行动自然发生。' },
    { type: '书', title: 'The Creative Act', note: '创作不是一次灵感，而是一种持续观察的方式。' },
    { type: '工具', title: 'Obsidian', note: '让零散想法逐渐形成连接。' },
    { type: '工具', title: 'Raycast', note: '把高频动作缩短成一次明确的意图。' },
    { type: '播客', title: 'Acquired', note: '从公司历史理解产品、战略与时间。' },
    { type: '网站', title: 'Are.na', note: '一个适合收集材料、保留偶然联系的地方。' },
  ],
  articles: [
    {
      id: 'a-place-of-my-own',
      title: '给自己留一块互联网自留地',
      date: '2026-09-16',
      category: '生活',
      summary: '信息流一直向前，但我想有一个地方，安静地保存自己的作品、思考和变化。',
      body: [
        { type: 'p', text: '这是一篇演示文章，用来展示个人网站里的阅读体验。正式使用时，可以把它换成你自己的第一篇文字。' },
        { type: 'h3', text: '一个可以慢慢生长的地方' },
        { type: 'p', text: '社交平台很适合分享当下：一张照片、一个链接、一句突然想到的话。但有些东西值得放得更久一些。做过的小项目、反复想过的问题、一次重要的选择，它们需要一个能被重新找到的地方。' },
        { type: 'p', text: '个人网站可以很小。没有复杂的功能，没有需要每天更新的压力。它只是一个稳定的入口，让别人认识你，也让你回头看看自己走过的路。' },
        { type: 'quote', text: '不必等到有了值得展示的成果，才开始记录。记录本身，也会让事情发生。' },
        { type: 'h3', text: '先从三件小事开始' },
        { type: 'ul', items: ['写一段真正像自己的介绍。', '放上一个愿意给朋友看的作品。', '记下一件最近想明白的事。'] },
        { type: 'p', text: '剩下的可以慢慢补。一个有生命力的网站，不一定在第一天就很完整。它会和它的主人一起变化。' },
      ],
    },
    {
      id: 'small-things',
      title: '把小东西做完，也是一种能力',
      date: '2026-09-10',
      category: '创造',
      summary: '比起不断开启新的项目，我更想练习把一个简单的想法，做到真正可用。',
      body: [
        { type: 'p', text: '这是一篇演示文章，展示如何用纯前端页面承载完整的文字内容。' },
        { type: 'p', text: '一个新想法最迷人的时候，常常是它还没有开始的时候。可能性很多，限制还没有出现，连细节都是自由的。真正动手以后，问题才一个个浮出来。' },
        { type: 'h3', text: '缩小范围，让它成立' },
        { type: 'p', text: '如果想做一个笔记工具，就先做到能写下、保存、再找到一条笔记。先让最小的使用过程完整，再决定要不要加标签、搜索或者分享。' },
        { type: 'quote', text: '完成不等于完美。完成意味着：有人可以开始使用它了。' },
        { type: 'p', text: '一个完成的小项目会给出真实反馈。它让模糊的问题变得具体，也让下一步更容易判断。' },
      ],
    },
    {
      id: 'tools-and-attention',
      title: '好的工具，应该让人忘记工具本身',
      date: '2026-09-03',
      category: '技术',
      summary: '我喜欢那些不争夺注意力的设计：打开就能用，用完就可以离开。',
      body: [
        { type: 'p', text: '这是一篇演示文章。你可以在内容配置中替换标题、分类、摘要和正文。' },
        { type: 'p', text: '评价一个工具时，我们很容易数它有多少功能。但使用工具的人通常只想完成眼前的一件事：找到文件、写下一段话、把一个链接分享出去。' },
        { type: 'h3', text: '减少需要做的决定' },
        { type: 'p', text: '合理的默认值、清楚的按钮文案、可以撤回的操作，都会让工具变得轻松。它们没有特别显眼，却决定了使用时是否顺畅。' },
        { type: 'p', text: '做自己的项目时，可以反复问一个问题：用户来到这个页面，下一步要做什么？如果答案很清楚，就让那件事更容易发生。' },
      ],
    },
  ],
  projects: [
    {
      id: 'personal-space',
      name: 'Personal Space',
      subtitle: '一个持续生长的个人空间',
      description: '用一个轻盈的网站，放下作品、文字，以及值得记住的想法。',
      category: '网站',
      tags: ['HTML', 'CSS', 'JavaScript'],
      artwork: 'browser',
      status: '当前网站',
      url: '',
      source: '',
      body: [
        { type: 'p', text: '你正在浏览的就是这个项目：一个以阅读和展示为核心的个人主页。' },
        { type: 'h3', text: '一个小空间，几个简单的入口' },
        { type: 'ul', items: ['首页：自我介绍和最近更新。', '文字：按分类浏览、搜索和阅读文章。', '作品：展示项目的想法与实现。', '随想：保存简短的思考片段。'] },
        { type: 'p', text: '页面支持深浅色切换和手机浏览。所有内容随网页一起保存，不需要登录或数据库。' },
      ],
    },
    {
      id: 'a-moment',
      name: 'A Moment',
      subtitle: '给专注留一点空间',
      description: '一个只关心当下的计时器想法，让开始比计划更简单。',
      category: '工具',
      tags: ['专注', '极简设计'],
      artwork: 'timer',
      status: '概念示例',
      url: '',
      source: '',
      body: [
        { type: 'p', text: '这是一个项目展示示例，用来演示如何介绍尚在构思中的作品。此处没有可运行的计时器。' },
        { type: 'h3', text: '想解决的问题' },
        { type: 'p', text: '开始一件事之前，我们有时会花太多时间计划。这个想法把操作收敛成选择一个时间段，然后开始。' },
        { type: 'h3', text: '预期的体验' },
        { type: 'ul', items: ['一次只关注一件事。', '以安静的视觉展示剩余时间。', '结束后留一小段休息时间。'] },
      ],
    },
    {
      id: 'pocket-notes',
      name: 'Pocket Notes',
      subtitle: '装进口袋的灵感本',
      description: '给转瞬即逝的想法一个落脚点，以后再慢慢整理。',
      category: '工具',
      tags: ['记录', '本地优先'],
      artwork: 'notes',
      status: '概念示例',
      url: '',
      source: '',
      body: [
        { type: 'p', text: '这是一个项目展示示例，并未实现独立的笔记应用。你可以用自己的真实作品替换这张卡片。' },
        { type: 'p', text: '想法不总是在电脑前出现。一个随手能记、之后能找回的小工具，可能比复杂的知识管理系统更适合起步。' },
        { type: 'quote', text: '先把想法接住，再决定它会长成什么。' },
      ],
    },
    {
      id: 'tiny-scripts',
      name: 'Tiny Scripts',
      subtitle: '让重复的事情少一点',
      description: '一些日常自动化的小脚本，从整理文件到处理文本。',
      category: '开源',
      tags: ['自动化', '开发工具'],
      artwork: 'terminal',
      status: '概念示例',
      url: '',
      source: '',
      body: [
        { type: 'p', text: '这是一个开源项目展示示例，暂未关联真实代码仓库。' },
        { type: 'h3', text: '从重复中发现问题' },
        { type: 'p', text: '当同一件手工操作出现好几次，就可以试着把它变成一个脚本。范围可以很小，输入输出清楚就好。' },
        { type: 'p', text: '真实项目可以在这里补充使用场景、安装方式，以及源码和演示地址。' },
      ],
    },
  ],
  ideas: [
    { date: '2026-09-15', title: '先做一个可以用的版本', text: '很多事情不用一次想清楚。\n先做出一个能被使用的小版本，真实的反馈会告诉你下一步。', tags: ['创造', '从小开始'] },
    { date: '2026-09-08', title: '留一点不被安排的时间', text: '散步的时候、发呆的时候、读一本不为解决问题的书的时候，偶尔会碰到新的想法。好奇心也需要空白。', tags: ['日常', '好奇心'] },
    { date: '2026-09-01', title: '写下来，才看得见', text: '脑子里觉得已经想明白的事，写成几句话时，往往还能发现新的问题。记录是一种慢一点的思考。', tags: ['写作', '思考'] },
    { date: '2026-08-25', title: '自己的节奏', text: '不一定每个爱好都要做成项目，也不一定每个项目都要有宏大的目标。\n有时候，只是因为喜欢。', tags: ['生活'] },
  ],
};
