window.SITE_CONTENT = {
  // 模板的示例内容：复制成 content.js 再逐项改成你自己的。人物、公司与经历都是虚构的，不引用任何图片或音乐文件。
  // 通用测试（scripts/site.test.mjs）也拿这份内容当样本，改它时保持两家公司都在。
  profile: {
    name: 'ada',
    siteTitle: "Ada's Galaxy",
    intro: '写代码，做设计，记录有意思的想法',
    motto: 'Stay Curious',
    description: '一个放作品、文字、实验和问题的个人空间。',
    focus: [
      '前端工程：设计系统与数据可视化',
      '数据工具：把一次性的分析做成可复用的小工具',
      '写作：技术笔记与读书记录',
    ],
    location: '中国 杭州市',
    locationEn: 'CHINA · HANGZHOU',
    now: 'Building small tools that make data easier to read.',
    nowNote: '把复杂的东西做得好懂一点。',
    email: '',
    github: '',
    demo: true,
  },
  about: {
    lead: '我喜欢把复杂的东西拆开，再拼成别人一眼就能看懂的样子。',
    paragraphs: [
      '这里是一段关于你自己的介绍：你在做什么、为什么做、做到了哪一步。写成你会对朋友说的话就好。',
      {
        type: 'layers',
        intro: '我目前投入最多的几件事：',
        items: [
          { title: '设计系统', text: '把按钮、表格、图表这些反复出现的东西整理成一套组件，让新页面一天就能搭起来。' },
          { title: '数据可视化', text: '一张图只回答一个问题；回答不了的，就拆成两张。' },
          { title: '写作', text: '把想明白的事写下来，也给还没想明白的事留个位置。' },
        ],
        outro: '三件事其实是一件事：让信息更容易被理解。',
      },
      '第三段可以写写工作之外的你。',
    ],
    facts: [
      { label: '职业经历', profile: 'role' },
      { label: '所在地区', profile: 'location' },
      { label: '常用语言', value: 'TypeScript, Python' },
      { label: '长期兴趣', value: '可视化、排版、长跑' },
    ],
  },
  experiments: [
    {
      id: 'chart-render',
      name: '万点折线图的渲染方式',
      status: '已完成',
      date: '2026-08',
      description: '同一份 1 万点的数据，SVG 与 Canvas 各画一次，比较首屏时间。',
      tags: ['Frontend', 'Performance'],
      compare: ['SVG', 'Canvas'],
      metric: { label: '首屏渲染时间', before: '420 ms', after: '95 ms' },
      hypothesis: '点数上万之后，DOM 节点本身就是瓶颈，换成 Canvas 应该快一个量级。',
      setup: [
        ['数据', '10,000 个点的时间序列'],
        ['环境', '同一台笔记本，同一个浏览器，各跑 20 次取中位数'],
      ],
      metrics: [
        { label: '首屏渲染时间', before: '420 ms', after: '95 ms' },
        { label: '内存占用', before: '58 MB', after: '21 MB' },
      ],
      charts: [
        {
          title: '点数与首屏渲染时间',
          x: { label: '点数', unit: 'k', scale: 'log' },
          y: { label: '渲染时间', unit: 'ms', min: 0, max: 450 },
          series: [
            { name: 'SVG', role: 'baseline', points: [[1, 48], [2, 90], [5, 210], [10, 420]] },
            { name: 'Canvas', role: 'result', points: [[1, 22], [2, 34], [5, 60], [10, 95]] },
          ],
          references: [],
        },
      ],
      findings: [
        '一千点以内两者差不多，SVG 还更好调样式。',
        '到一万点，SVG 的时间几乎随点数线性增长，Canvas 增长平缓。',
      ],
      conclusion: '图表点数可能上万时，用 Canvas；交互和样式要求高、点数少时，SVG 更省事。',
      references: [],
    },
  ],
  experience: [
    {
      id: 'acme',
      company: 'Acme',
      modeName: 'Acme',
      privateMarkers: ['Acme Corporation', 'Project Roadrunner'],
      profileRole: 'Frontend Engineer at Acme',
      start: '2024-07',
      roles: [
        {
          title: 'Frontend Engineer',
          start: '2024-07',
          current: true,
          highlights: ['负责数据看板的设计系统，把新页面的搭建时间从一周缩到一天。'],
          skills: ['TypeScript', 'React', 'D3'],
        },
      ],
    },
    {
      id: 'globex',
      company: 'Globex',
      modeName: 'Globex',
      privateMarkers: ['Globex Corporation', 'Project Northwind'],
      profileRole: 'Data Engineering Intern at Globex',
      start: '2023-07',
      roles: [
        {
          title: 'Data Engineering Intern',
          start: '2023-07',
          end: '2023-12',
          highlights: ['把每周手工整理的报表改成定时任务，省下每周半天。'],
          skills: ['Python', 'SQL'],
        },
      ],
    },
  ],
  journey: [
    {
      period: '2019.09 — 2023.06',
      title: '某某大学',
      degree: '本科',
      major: '计算机科学与技术',
    },
  ],
  library: [
    {
      type: '书',
      title: 'The Visual Display of Quantitative Information',
      tags: ['可视化', '设计'],
      venue: 'Edward Tufte',
      note: '每一滴墨水都要为数据服务。',
      url: 'https://www.edwardtufte.com/tufte/books_vdqi',
    },
    {
      type: '文章',
      title: 'Write Simply',
      tags: ['写作'],
      venue: 'Paul Graham',
      note: '能用短词就别用长词。',
      url: 'https://paulgraham.com/simply.html',
    },
  ],
  articles: [
    {
      id: 'one-chart-one-question',
      title: '一张图只回答一个问题',
      date: '2026-09-20',
      category: '技术',
      summary: '图表画不清楚，往往不是因为不会画，而是想让它回答太多问题。',
      body: [
        { type: 'p', text: '每次画图之前，先写下这张图要回答的那一个问题。写不出来，就先别画。' },
        { type: 'h3', text: '拆开比堆叠更好懂' },
        { type: 'p', text: '四条线挤在一张图里，读者要来回对颜色；拆成四张小图，一眼就能比。' },
      ],
    },
    {
      id: 'first-week',
      title: '新工作的第一周',
      date: '2026-09-05',
      category: '工作',
      summary: '先听、先记、先问，别急着改。',
      body: [
        { type: 'p', text: '第一周最有用的事，是把每个人说过的「这里有坑」都记下来。' },
      ],
    },
    {
      id: 'running-notes',
      title: '跑步的时候想什么',
      date: '2026-08-18',
      category: '随想',
      summary: '大部分时候什么都不想，这正是跑步的好处。',
      body: [
        { type: 'quote', text: '跑步时脑子空下来，想法反而自己冒出来。' },
      ],
    },
  ],
  projectFacets: [
    { key: 'type', label: '类型', values: [{ value: '平台', en: 'Platform' }, { value: '框架', en: 'Framework' }, { value: '应用', en: 'App' }, { value: '工具', en: 'Tool' }] },
    { key: 'uses', label: '使用', multiple: true, values: [{ value: 'Web' }, { value: 'CLI' }, { value: 'SDK' }] },
    { key: 'code', label: '代码', values: [{ value: '开源', en: 'Open source' }, { value: '未开源', en: 'Not open source' }] },
  ],
  projects: [
    {
      id: 'chart-kit',
      name: 'Chart Kit',
      tagline: '一套看板图表组件',
      subtitle: '十几种常用图表，一份配置就能画出来',
      description: '把团队反复手写的图表整理成组件：同一份数据，换一个参数就能在折线、柱状和热力图之间切换。',
      type: '工具',
      uses: ['Web', 'SDK'],
      code: '开源',
      tags: ['TypeScript', 'D3'],
      artwork: 'browser',
      status: '持续维护',
      url: '',
      source: '',
      body: [
        { type: 'p', text: '在这里写这个作品解决什么问题、怎么用、做到了哪一步。' },
        { type: 'h3', text: '为什么做它' },
        { type: 'p', text: '每个看板都在重复画同几种图，样式还各不相同。' },
      ],
    },
    {
      id: 'weekly-report',
      name: 'Weekly Report',
      subtitle: '每周一早上自动出现的报表',
      description: '一个定时脚本：拉数据、算指标、生成图表，再发到群里。',
      type: '工具',
      uses: ['CLI'],
      code: '未开源',
      tags: ['Python', 'SQL'],
      artwork: 'terminal',
      status: '内部使用',
      url: '',
      source: '',
      body: [
        { type: 'p', text: '作品详情支持段落、小标题、列表、引用、图片、参考链接和站内小工具，写法见 README。' },
      ],
    },
  ],
  music: { tracks: [] },
  comments: {
    provider: 'giscus',
    site: 'https://your-name.github.io/your-repo/',
    repo: 'your-name/your-repo',
    repoId: '',
    category: 'Announcements',
    categoryId: '',
  },
  ideas: [
    {
      id: 'good-default-chart',
      date: '2026-09-28',
      title: '什么样的图表默认值才算好？',
      text: '大多数人不会改图表的默认设置，所以默认值其实决定了大多数图长什么样。',
      tags: ['可视化'],
    },
    {
      id: 'notes-or-tools',
      date: '2026-09-10',
      title: '写笔记和做工具，哪个更能帮未来的自己？',
      text: '笔记记下了为什么，工具记下了怎么做。也许两者都需要，只是比例不同。',
      tags: ['方法'],
    },
  ],
};
